### ISSUE TITLE
Make Store async

### ISSUE THREAD

**Issue by bernardobelchior** [mqttjs/async-mqtt#18]
As of now, `async-mqtt` only transforms the sync client to async. 
The `mqtt.js` package has a [`Store`](https://github.com/mqttjs/MQTT.js#store) class that relies on callbacks. In my opinion, this would also be in the scope of this package.

Do you have any plans on implementing this? I can give a hand, if needed.

**Comment by RangerMauve** [comment]
What's the use case for a promise based store?

I think it'd be good to maintain compatibility with stores used in MQTT.js rather than fork the ecosystem.

It might be useful to create a new store which takes a async/await implemented store and wraps over all the method calls to use callbacks. That way you can use async-await, but have it usable in any version of MQTT.js

**Comment by bernardobelchior** [comment]
What I meant was to substitute the callback-based functions from the store for promise-based ones. 
When I suggested this, I was trying to use a store, but not anymore, so I understand if you don't to pursue something without a use :smile:

**Comment by RangerMauve** [comment]
Yeah, I think I'll close this for now until somebody else needs it. :)
