### ISSUE TITLE
Converting connect method to promise

### ISSUE THREAD

**Issue by Tabrizian** [mqttjs/async-mqtt#4]
What is your idea of converting the ```connect``` method to a promise too?
For example, connecting would become something like this:

```js
let mqtt = await MQTT.connect('tcp://somehost.com:1883')
```

**Comment by RangerMauve** [comment]
I actually did that initially, but I held off because this would prevent any chances of cancellation. I definately get the use-case you're proposing, but I think it might be better to place it under a different method name so that you could cancel initializing the client before it connects.

**Comment by Tabrizian** [comment]
What is the use case of canceling an ongoing promise? It will be either rejected or fulfilled. What's the use case of cancelation?

**Comment by RangerMauve** [comment]
In my case, sometimes when I'm starting up the part of my application that uses the MQTT connection, a user will perform an action that requires a teardown of everything loaded so that a different view can be set up. If the connection hasn't completed yet, it can be ended prematurely, otherwise I would have to wait on the promise to resolve before I could destroy it, and it might cause race conditions. If I didn't have the constraint that user actions could destroy the connection, I wouldn't need to worry about it, so I think it would be good to allow for both.

**Comment by Tabrizian** [comment]
Oh, I see.  So you agree with adding it while keeping old event base too?

**Comment by RangerMauve** [comment]
Yeah. Specifically, I think that it would be useful to have a `connect` method which returns a client instance right away like you'd do with regular MQTT.js, and have a `connectAsync` or something which waits for the `connected` or `error` event to resolve or reject a promise.

**Comment by Tabrizian** [comment]
Perfect :100:

**Comment by RangerMauve** [comment]
That would be awesome. :D If it's a new method name, then it'd just be a minor version update.

**Comment by RangerMauve** [comment]
@pinoyyid Feel free to submit a pull request with a `connectAsync` method if you have time. 😀

Ideally with an accompanying test to make sure it works.

**Comment by cdupont** [comment]
Hi guys, this feature would be awesome.

**Comment by Tabrizian** [comment]
Sorry, I didn't had time to implement this :(

**Comment by TimSusa** [comment]
Gentlemen, 

almost beeing late here to the party. As already mentioned in the other issue. You can save yourself a lot of work and hazzle by just using promisify because all your mqtt.js stuff is already in nodejs callback style. Please be refered to:
https://hackernoon.com/node8s-util-promisify-is-so-freakin-awesome-1d90c184bf44

Example:
``` 
const util = require('util');

// Here we use util.promisify to convert the function to a promise
const waitAsync = util.promisify(wait);

//And here we use the promisified function. Cool huh?
waitAsync(1000)
  .then(data => console.log(data))
  .catch(err => console.error(`[Error]: ${err}`));
```  

Maybe, better with async and await, so @Tabrizian: Your example from above should then return a resolved Promise, where you should yield whatever your connection function returns. And please please do not forget to wrap your await calls in a try and catch block. 

Cheers!

**Comment by TimSusa** [comment]
> What is the use case of canceling an ongoing promise? It will be either rejected or fulfilled. What's the use case of cancelation?

Bluebird has a cancelation feature: http://bluebirdjs.com/docs/api/cancellation.html

**Comment by 123joshuawu** [comment]
Hello super late to the party :p

Would something like this work?
```javascript
function connectAsync(brokerURL, opts) {
	const client = mqtt.connect(brokerURL, opts);
	const asyncClient = new AsyncClient(client);

	return new Promise((resolve, reject) => {
		let connectOnceListener = (connack) => {
			client.removeListener('error', errorOnceListener);
			client.removeListener('end', endOnceListener);
			resolve(asyncClient);
		};
		client.prependOnceListener('connect', connectOnceListener);

		let errorOnceListener = (err) => {
			client.removeListener('end', endOnceListener);
			client.removeListener('connect', connectOnceListener);
			reject(err);
		};
		client.prependOnceListener('error', errorOnceListener);

		let endOnceListener = () => {
			client.removeListener('error', errorOnceListener);
			client.removeListener('connect', connectOnceListener);
			resolve(asyncClient);
		};
		client.prependOnceListener('end', endOnceListener);
	});
}
```

Just resolves on 'connect' and 'end' (allowing cancellation?), and rejects on 'error'. Also removes remaining listeners upon promise resolution. Can also add a reject on 'disconnect' if retries are not desired.

**Comment by Tabrizian** [comment]
Thanks for the suggestion @123joshuawu. Would you like to submit a PR and we can then discuss it?

**Comment by Tabrizian** [comment]
I think we can now close this issue! 🎉

**Comment by iriekun** [comment]
Can somebody help? I need to convert client.on("message", (topic, message) to promise. I wrapped it in a promise as this ```
const getMessageAsync = () => {
  return new Promise((resolve, reject) => {
    client.on("message", (topic, message) => {
      resolve(message);
    });
  });
}
```
but then it didn't return message correctly as using callback. Basically, it return only one data point!!!

**Comment by RangerMauve** [comment]
@iriekun Hey! Promises aren't the right data structure to use in this case. Promises are made for getting a single data point. I'd suggest looking into async iterators and how to use them with eventemitters. 😁
