### ISSUE TITLE
Question: Request/Response syntax?

### ISSUE THREAD

**Issue by MatteoJoliveau** [mqttjs/async-mqtt#5]
Hi everyone,
I made a small wrapper around this client to support a clean request/response syntax with promise support.
It gives every request a unique id (using [ULID](https://github.com/ulid/javascript)) and uses it to associate request messages with response messages via one-shot topics.
This is the syntax:  
```javascript
// request topic will be "my/topic/request/123456"
sendRequest("my/topic", "Hello!").then((res) => {
        /*
            res ={
                topic: ""my/topic/response/123456",
                payload: Buffer()
            }
        */
    }, (err) => console.error)
```
Example topics:  
* Request: mynamespace/request/{id}
* Response: mynamespace/response/{id}

## Question
Would it be interesting to include in this respository? Otherwise I'll just make a wrapper on my own but I don't want to segment the userbase just for a single feature like this.
If interested I'd love to hear your suggestions/change you'd make!

**Comment by Tabrizian** [comment]
Hi there!

Your idea is actually amazing and I find it very interesting, but the purpose of this repository is to only provide a promise wrapper around the MQTT.js. I don't think that this relates to here.

But it's an idea that I actually craved about. To define routes for MQTT.

Also, I think that the topic you mentioned should be generalized more. For example instead of converting ```my/topic``` to ```my/topic/request/{id}``` maybe its better to use it this way ```my/topic/request/{id}``` to better describe the topic.

**Comment by MatteoJoliveau** [comment]
Hello!
Yeah you're right, I thought it was a good idea to not have 65 different clients with 65 different features each, but I think I'll just make my own at this point to not bloat this one.

Can you elaborate on the part about topics? I didn't understand what you mean.

**Comment by RangerMauve** [comment]
Hi @MatteoJoliveau, I agree with @Tabrizian about your requests model not being in-line with the goal of this library. This client is really made to be general purpose and lower level.
The request thing you have is interesting, but I think it's very specific to your use case.

If you end up using this as a dependency, I think it would be fine for us to mention your library in the README in a `projects using this` section so that people can find your library more easily.

**Comment by MatteoJoliveau** [comment]
Hi @RangerMauve, that's a good idea, thanks for your replies. I'll let you know if/when I'll publish the project
